create table if not exist profiles (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  category character varying null,
  type character varying null,
  line character varying null,
  color character varying null,
  status character varying null,
  quantity smallint null,
  site character varying null,
  width numeric null,
  material character varying null,
  last_update timestamp with time zone null,
  constraint profiles_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists idx_profiles_category on public.profiles using btree (category) TABLESPACE pg_default;

create index IF not exists idx_profiles_type on public.profiles using btree (type) TABLESPACE pg_default;