--- PROFILES ---

create table if not exists public.profiles (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  code character varying not null,
  line character varying not null,
  color character varying not null,
  status character varying not null,
  quantity smallint not null,
  site character varying not null,
  width numeric not null,
  material character varying not null,
  image_id bigint null,
  last_update timestamp with time zone null,
  constraint profiles_pkey primary key (id),
  constraint fk_profiles_separated_for_work foreign KEY (separated_for_work_id) references works (id) on update CASCADE on delete set null,
  constraint quantity_positive check ((quantity >= 0)),
  constraint width_range check ((width > (0)::numeric))
) TABLESPACE pg_default;

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS separated_for_work_id BIGINT;

ALTER TABLE public.profiles
ADD CONSTRAINT IF NOT EXISTS fk_profiles_separated_for_work
FOREIGN KEY (separated_for_work_id)
REFERENCES public.works(id)
ON DELETE SET NULL
ON UPDATE CASCADE;

--- LINES ---

create table if not exists public.lines (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name_line character varying not null,
  opening character varying not null,
  constraint Lines_pkey primary key (id),
  constraint lines_name_line_key unique (name_line),
  constraint opening_valid check (
    (
      (opening)::text = any (
        (
          array[
            'Aluminio'::character varying,
            'PVC'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create table if not exists public.colors (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  line_name character varying not null,
  name_color character varying not null,
  constraint colors_pkey primary key (id),
  constraint colors_color_line_unique unique (name_color, line_name),
  constraint colors_line_name_fkey foreign KEY (line_name) references lines (name_line) on update CASCADE
) TABLESPACE pg_default;

create table public.codes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name_code character varying not null,
  line_name character varying null,
  constraint codes_pkey primary key (id),
  constraint codes_name_line_unique unique (name_code, line_name),
  constraint codes_line_name_fkey foreign KEY (line_name) references lines (name_line) on update CASCADE
) TABLESPACE pg_default;

create table if not exists public.sites (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name_site character varying not null,
  constraint sites_pkey primary key (id),
  constraint sites_name_site_key unique (name_site)
) TABLESPACE pg_default;


create table if not exists public.ironworks_category (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  ironwork_line character varying null,
  ironwork_code character varying not null,
  ironwork_description character varying null,
  ironwork_color character varying not null,
  ironwork_quantity_for_lump bigint not null,
  ironwork_quantity_lump bigint not null,
  ironwork_quantity bigint not null,
  ironwork_site character varying not null,
  image_id bigint null,
  ironwork_material character varying not null,
  ironwork_price numeric(10, 2) null,
  ironwork_category character varying not null,
  last_update timestamp without time zone null,
  ironwork_brand character varying null,
  constraint ironworks_category_pkey primary key (id),
  constraint chk_ironwork_price_non_negative check ((ironwork_price >= (0)::numeric)),
  constraint chk_ironwork_quantity_for_lump_non_negative check ((ironwork_quantity_for_lump >= 0)),
  constraint chk_ironwork_quantity_lump_non_negative check ((ironwork_quantity_lump >= 0)),
  constraint chk_ironwork_quantity_non_negative check ((ironwork_quantity >= 0))
) TABLESPACE pg_default;

create table if not exists public.accesories_category (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  accessory_line character varying null,
  accessory_code character varying not null,
  accessory_description character varying null,
  accessory_color character varying not null,
  accessory_quantity_for_lump bigint not null,
  accessory_quantity_lump bigint not null,
  accessory_quantity bigint not null,
  accessory_site character varying not null,
  image_id bigint null,
  accessory_material character varying not null,
  accessory_price numeric(10, 2) null,
  accessory_category character varying not null,
  last_update timestamp without time zone null,
  accessory_brand character varying null,
  constraint accesories_category_pkey primary key (id),
  constraint chk_accessory_price_non_negative check ((accessory_price >= (0)::numeric)),
  constraint chk_accessory_quantity_for_lump_non_negative check ((accessory_quantity_for_lump >= 0)),
  constraint chk_accessory_quantity_lump_non_negative check ((accessory_quantity_lump >= 0)),
  constraint chk_accessory_quantity_non_negative check ((accessory_quantity >= 0))
) TABLESPACE pg_default;

create table public.supplies_category (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  supply_line character varying null,
  supply_code character varying not null,
  supply_description character varying null,
  supply_color character varying not null,
  supply_quantity_for_lump bigint not null,
  supply_quantity_lump bigint not null,
  supply_quantity bigint not null,
  supply_site character varying not null,
  image_id bigint null,
  supply_material character varying not null,
  supply_price numeric(10, 2) null,
  supply_category character varying not null,
  last_update timestamp without time zone null,
  supply_brand character varying null,
  constraint supplies_category_pkey primary key (id),
  constraint chk_supply_price_non_negative check ((supply_price >= (0)::numeric)),
  constraint chk_supply_quantity_for_lump_non_negative check ((supply_quantity_for_lump >= 0)),
  constraint chk_supply_quantity_lump_non_negative check ((supply_quantity_lump >= 0)),
  constraint chk_supply_quantity_non_negative check ((supply_quantity >= 0))
) TABLESPACE pg_default;

create table public.clients (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying not null,
  last_name character varying not null,
  phone_number character varying null,
  locality character varying null,
  email character varying null,
  cover text null,
  contact_method text null,
  seller_id bigint null,
  constraint clients_pkey primary key (id)
) TABLESPACE pg_default;

create table public.sellers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying not null,
  constraint sellers_pkey primary key (id)
) TABLESPACE pg_default;

create table public.stock_thresholds (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  item_id bigint not null,
  item_category character varying not null,
  yellow_threshold bigint not null default 5,
  red_threshold bigint not null default 0,
  constraint stock_thresholds_pkey primary key (id),
  constraint stock_thresholds_item_category_unique unique (item_id, item_category)
) TABLESPACE pg_default;
alter table public.clients
  add constraint clients_seller_id_fkey
  foreign key (seller_id) references public.sellers (id)
  on update cascade on delete set null;

{/*
  RECORDAR LOS BUCKETS
*/}

create table public.works (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  locality character varying null,
  address character varying null,
  zone character varying null,
  hood character varying null,
  client_id bigint null,
  status character varying null,
  architect character varying null,
  notes character varying[] null,
  balance_id bigint null,
  constraint works_pkey primary key (id),
  constraint works_client_id_fkey foreign KEY (client_id) references clients (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.events (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  type character varying null,
  description character varying null,
  title character varying null,
  client character varying null,
  location character varying null,
  date date null,
  address character varying null,
  status character varying null,
  is_overdue boolean null default false,
  remember boolean null default false,
  constraint events_pkey primary key (id)
) TABLESPACE pg_default;

{/* 
  Para los eventos, correr en SQL editor de Supabase:
*/}

SELECT * FROM pg_extension WHERE extname = 'pg_cron';

CREATE EXTENSION IF NOT EXISTS pg_cron;

UPDATE public.events
SET is_overdue = true
WHERE date < CURRENT_DATE
  AND status = 'pending'
  AND is_overdue = false;

SELECT cron.schedule(
  'mark-overdue-events',
  '5 0 * * *',
  $$
  UPDATE public.events
  SET is_overdue = true
  WHERE date < CURRENT_DATE
    AND status = 'pending'
    AND is_overdue = false;
  $$
);

SELECT jobid, jobname, schedule
FROM cron.job;

create table public.checklists (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  work_id bigint null,
  items jsonb null,
  description character varying null,
  progress bigint null,
  name character varying null,
  type_opening character varying null,
  width double precision null,
  height double precision null,
  notes text null,
  constraint checklists_pkey primary key (id),
  constraint checklists_work_id_fkey foreign KEY (work_id) references works (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;
  
create table public.users (
  id bigint generated by default as identity not null,
  username character varying not null,
  role character varying not null,
  password character varying not null,
  constraint users_pkey primary key (id),
  constraint users_username_key unique (username)
) TABLESPACE pg_default;

create table public.balances (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  start_date date null,
  contract_date_usd numeric null,
  client_id bigint null,
  usd_current numeric null,
  budget_id bigint null,
  notes text null,
  balance_amount_ars numeric null,
  balance_amount_usd numeric null,
  constraint balances_pkey primary key (id),
  constraint balances_budget_id_fkey foreign KEY (budget_id) references budgets (id) on update CASCADE,
  constraint balances_client_id_fkey foreign KEY (client_id) references clients (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table if not exists public.balance_transactions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  balance_id bigint null,
  date date null,
  amount numeric null,
  quote_usd numeric null,
  usd_amount numeric null,
  notes text null,
  payment_method character varying null,
  is_extra_amount boolean not null default false,
  constraint balance_transactions_pkey primary key (id),
  constraint balance_transactions_balance_id_fkey foreign KEY (balance_id) references balances (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table if not exists public.folder_budgets (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  work_id bigint null,
  client_id bigint null,
  constraint folder_budgets_pkey primary key (id),
  constraint folder_budgets_client_id_fkey foreign KEY (client_id) references clients (id) on update CASCADE on delete CASCADE,
  constraint folder_budgets_work_id_fkey foreign KEY (work_id) references works (id) on update CASCADE
) TABLESPACE pg_default;

create table if not exists public.budgets (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  accepted boolean null,
  pdf_url text null,
  pdf_path text null,
  number text null,
  amount_ars numeric null,
  version text null,
  type text null,
  folder_budget_id bigint null,
  amount_usd numeric null,
  sold boolean null,
  lost boolean null,
  usd_quote numeric null,
  date_of_sale timestamp with time zone null,
  constraint budgets_pkey primary key (id),
  constraint budgets_folder_budget_id_fkey foreign KEY (folder_budget_id) references folder_budgets (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table if not exists public.claims (
  id bigint generated by default as identity not null,
  created_at timestamp without time zone not null,
  client_id bigint null,
  work_zone text null,
  daily boolean null,
  alum_pvc text null,
  attend text null,
  description text null,
  date date null,
  resolved boolean null,
  resolution_date date null,
  work_locality text null,
  work_address text null,
  work_hood text null,
  constraint claims_pkey primary key (id)
) TABLESPACE pg_default;

create table if not exists public.files_client (
  id bigint generated by default as identity not null,
  uploaded_at timestamp with time zone not null default now(),
  client_id bigint null,
  path text null,
  title text null,
  description text null,
  checklist_id bigint null,
  claim_id bigint null,
  constraint files_client_pkey primary key (id),
  constraint files_client_checklist_id_fkey foreign KEY (checklist_id) references checklists (id) on update CASCADE on delete CASCADE,
  constraint files_client_claim_id_fkey foreign KEY (claim_id) references claims (id) on update CASCADE on delete CASCADE,
  constraint files_client_client_id_fkey foreign KEY (client_id) references clients (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.gallery_profiles (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  image_url text null,
  image_path text null,
  line text null,
  code text null,
  material_type text null,
  constraint gallery_profiles_pkey primary key (id)
) TABLESPACE pg_default;

create table public.gallery_stock (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  category text null,
  code text null,
  image_url text null,
  image_path text null,
  constraint gallery_stock_pkey primary key (id)
) TABLESPACE pg_default;

--- SURVEYS ---

create table public.surveys (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  budget_id bigint not null,
  client_id bigint not null,
  notes text null,
  due_date date null,
  constraint surveys_pkey primary key (id),
  constraint surveys_budget_id_unique unique (budget_id),
  constraint surveys_budget_id_fkey foreign KEY (budget_id) references budgets (id) on update CASCADE on delete CASCADE,
  constraint surveys_client_id_fkey foreign KEY (client_id) references clients (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists surveys_client_id_idx on public.surveys using btree (client_id) TABLESPACE pg_default;

create table public.survey_items (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  survey_id bigint not null,
  label text not null,
  completed boolean not null default false,
  "order" integer not null default 0,
  constraint survey_items_pkey primary key (id),
  constraint survey_items_survey_id_fkey foreign KEY (survey_id) references surveys (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists survey_items_survey_id_idx on public.survey_items using btree (survey_id) TABLESPACE pg_default;

--- SURVEY TAGS ---

create table if not exists public.survey_tags (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying not null,
  color character varying not null,
  constraint survey_tags_pkey primary key (id),
  constraint survey_tags_name_unique unique (name)
) TABLESPACE pg_default;


create table if not exists public.survey_tag_assignments (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  survey_id bigint not null,
  tag_id bigint not null,
  constraint survey_tag_assignments_pkey primary key (id),
  constraint survey_tag_assignments_survey_id_fkey foreign KEY (survey_id) references surveys (id) on update CASCADE on delete CASCADE,
  constraint survey_tag_assignments_tag_id_fkey foreign KEY (tag_id) references survey_tags (id) on update CASCADE on delete CASCADE,
  constraint survey_tag_assignments_unique unique (survey_id, tag_id)
) TABLESPACE pg_default;


create index if not exists survey_tag_assignments_survey_id_idx on public.survey_tag_assignments using btree (survey_id);
create index if not exists survey_tag_assignments_tag_id_idx on public.survey_tag_assignments using btree (tag_id);
