create table if not exists public.survey_tags (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying not null,
  color character varying not null,
  constraint survey_tags_pkey primary key (id),
  constraint survey_tags_name_unique unique (name)
) TABLESPACE pg_default;

create table if not exists public.survey_tag_assignments (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  survey_id bigint not null,
  tag_id bigint not null,
  constraint survey_tag_assignments_pkey primary key (id),
  constraint survey_tag_assignments_survey_id_fkey foreign KEY (survey_id) references surveys (id) on update CASCADE on delete CASCADE,
  constraint survey_tag_assignments_tag_id_fkey foreign KEY (tag_id) references survey_tags (id) on update CASCADE on delete CASCADE,
  constraint survey_tag_assignments_unique unique (survey_id, tag_id)
) TABLESPACE pg_default;

create index if not exists survey_tag_assignments_survey_id_idx on public.survey_tag_assignments using btree (survey_id);
create index if not exists survey_tag_assignments_tag_id_idx on public.survey_tag_assignments using btree (tag_id);
